#!/usr/bin/env php
<?php

require "Client.php";

$monitor = new Monitor\Client('RAKETKA_ID', 12345, 'http://monitor/server');

$data = array();

parse_str(implode('&', array_slice($argv, 1)), $data);

var_dump($data);
exit;

$monitor->log($commit_id, 'Pushed', Monitor\Client::FLAG_CREATED);
$monitor->log($commit_id, 'Deploying');
$monitor->log($commit_id, 'Deployed', Monitor\Client::FLAG_FINISHED);


class CMD {
	public static function getLastCommitID()
	{
		$output = null;
		$retval = null;

		$command = 'git log -n1 --format="%H"';

		exec($command, $output, $retval);

		return $output[0];
	}
}